FROM ubuntu:22.10

RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y openssh-server openssh-client iputils-ping net-tools vim && \
    apt-get clean

# Crear usuario "prueba"
RUN useradd -ms /bin/bash prueba && echo "prueba:prueba" | chpasswd

# Ajustar configuración de sshd
RUN sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN mkdir -p /var/run/sshd

# Exponer puerto
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
